spring.application.name=movie-service
spring.profiles.active=dev

server.servlet.context-path=/movies

# ===============================
# = SECURITY / JWT
# ===============================
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=${JWT_JWKS_URI:http://localhost:8081/.well-known/jwks.json}

# ===============================
# = KAFKA
# ===============================
spring.kafka.bootstrap-servers=localhost:9092
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer
spring.kafka.producer.properties.spring.json.add.type.headers=false
spring.kafka.producer.properties.max.block.ms=10000

services.tickets.url=http://localhost:8085
services.users.url=http://localhost:8082